# Change these first
owner: Ohmlaws # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Ohmlaws
    url: https://ohmlaws.github.io
  - name: First Year
    url: https://ohmlaws.github.io/firstyear/
  - name: Second Year
    url: https://ohmlaws.github.io/secondyear/ 
  - name: Resistor Hub
    url: https://roniui.github.io/resistor/
  - name: Age Calculator
    url: https://roniui.github.io/date/calculator


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/ohmlaws/ohmlaws.github.io/refs/heads/main/assets/img/avatar.png
  name: Ohmlaws
  introTitle: "[OhmLaws](https://ohmlaws.github.io/) Site Uptime Stats"
#  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Home
      href: https://ohmlaws.github.io
  css: "@media (prefers-color-scheme: dark) { body { text-shadow: 0px 0px 6px rgba(0,0,0,1) } }"
  

  favicon: https://raw.githubusercontent.com/ohmlaws/ohmlaws.github.io/refs/heads/main/assets/img/favicons/favicon-96x96.png
  faviconSvg: https://raw.githubusercontent.com/ohmlaws/ohmlaws.github.io/refs/heads/main/assets/img/favicons/favicon.svg

i18n:
  footer: This page is powered by [Upptime](https://upptime.js.org)
  locale: en-IN

workflowSchedule:
  uptime: "*/5 * * * *"                # always unchanged

  responseTime: "0 10,22 * * *"        # 3:30 AM/PM IST
  summary: "1 10,22 * * *"       # run 5 minutes after responseTime
  graphs: "2 10,22 * * *"      # run 10 minutes after responseTime
  staticSite: "3 10,22 * * *"      # final build & deploy after everything
  
  updateTemplate: "0 0 * * *"          # 5:30 AM IST
  updates: "0 3 * * *"          # 8:30 AM IST
  # ...
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
